### ISSUE TITLE
Missing test_model File in Your GitHub Repository

### ISSUE THREAD

**Issue by Hongzunhei** [mfazampour/ProRegGAN#3]
Dear Mohammad Farid Azampour, 
﻿ 
I recently read your article and found it very insightful. I am currently trying to reproduce your work using the code you provided on GitHub. I have successfully trained the multi-task model, but when I proceeded to test it, I realized that there seems to be a missing file named test_model. This file seems to be necessary, as it likely contains the get_current_dice() function and so on required for the testing phase. 
﻿ 
Would it be possible for you to provide the missing test_model file or point me in the right direction to properly test the model as intended? 
﻿ 
Thank you very much for your time and assistance. 
﻿ 
Best regards！

**Comment by mfazampour** [comment]
Dear @Hongzunhei , I updated the code last week, I hope now it runs without any problem. Let me know if there is something missing. It might still be that when distilling the code to put it online I introduced some errors

**Comment by Hongzunhei** [comment]
Dear @mfazampour ，Thank you for your hard work. However, I'm still encountering some issues during execution. I'm testing the model cut3d_multitask_modle, and noticed that when calling the multitask_parent.py file, the is_train flag is set to FALSE, which causes the --similarity and --grad_loss_weight parameters to be ignored. I've already made the adjustments on my end, but it would be great if you could update it so that others can run the testing process smoothly as well. Additionally, I've added a feature to save the deformation field and the deformed moving_image and mask to facilitate observing the results. Once again, thank you for your efforts.
